### ISSUE TITLE
Output raw EPL

### ISSUE THREAD

**Issue by alexslade** [cassiomarques/zebra-epl#6]
Hi Cássio, 

Thanks for the work on this gem! Really useful, I've been poring through EPL docs for hours to get to grips with Eltron... 

I (and I imagine others) need to grab the raw EPL rather than a execute a command-line call. (Have you seen QZ.io? Pretty cool, websocket from your server to a local printing client). 

Would you be open to a PR that added another method: outputting the EPL instead of printing immediately? Looking at your code I think I'll just print the contents of the tempfile where you're storing the EPL. 

Thanks, 
~Alex

**Comment by cassiomarques** [comment]
Hi Alex, and sorry for taking SO long to reply. For whatever reason I didn't even see a issue had been open here.

Yeah, sounds like a good idea, if you still need it after all this time, a PR would be most welcome :-)

Thank you!

**Comment by alexslade** [comment]
Hi Cassio, 

I'm afraid I don't have that printer anymore, so I don't have a true way of verifying output is ok and works, so I think I'll have to close this for now.
